openapi: 3.0.3
info:
  title: Quaze
  description: |-
    You are welcome to test functionality of the Quaze backend service!
  version: 1.0.11
servers:
  - url: http://127.0.0.1:5000/
tags:
  - name: Config
    description: config

paths:
  /config/basytec:
    get:
      tags:
        - Config
      summary: Get Basytec config
      description: Returns the Basytec config
      responses:
        '200':
          description: Basytec config returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasytecConfig'          
        '404':
          description: No config found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Config
      summary: Update Basytec config
      description: Updates the Basytec config with the provided values
      requestBody:
        description: Basytec config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasytecConfig'
          application/xml:
            schema:
              $ref: '#/components/schemas/BasytecConfig'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BasytecConfig'
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: UpdateConfigError occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /config/gantner:
    get:
      tags:
        - Config
      summary: Get Gantner config
      description: Returns the Gantner config
      responses:
        '200':
          description: Gantner config returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GantnerConfig'          
        '404':
          description: No config found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Config
      summary: Update Gantner config
      description: Updates the Gantner config with the provided values
      requestBody:
        description: Gantner config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GantnerConfig'
          application/xml:
            schema:
              $ref: '#/components/schemas/GantnerConfig'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GantnerConfig'
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: UpdateConfigError occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /config/precitec:
    get:
      tags:
        - Config
      summary: Get Precitec config
      description: Returns the Precitec config
      responses:
        '200':
          description: Precitec config returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrecitecConfig'          
        '404':
          description: No config found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Config
      summary: Update Precitec config
      description: Updates the Precitec config with the provided values
      requestBody:
        description: Precitec config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrecitecConfig'
          application/xml:
            schema:
              $ref: '#/components/schemas/PrecitecConfig'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PrecitecConfig'
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: UpdateConfigError occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /config/rig:
    get:
      tags:
        - Config
      summary: Get Rig config
      description: Returns the Rig config
      responses:
        '200':
          description: Rig config returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RigConfig'          
        '404':
          description: No config found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Config
      summary: Update Rig config
      description: Updates the Rig config with the provided values
      requestBody:
        description: Rig config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RigConfig'
          application/xml:
            schema:
              $ref: '#/components/schemas/RigConfig'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RigConfig'
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: UpdateConfigError occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /config/general:
    get:
      tags:
        - Config
      summary: Get General config
      description: Returns the General config
      responses:
        '200':
          description: General config returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralConfig'          
        '404':
          description: No config found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Config
      summary: Update General config
      description: Updates the General config with the provided values
      requestBody:
        description: General config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneralConfig'
          application/xml:
            schema:
              $ref: '#/components/schemas/GeneralConfig'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GeneralConfig'
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: UpdateConfigError occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /config/acquisition:
    get:
      tags:
        - Config
      summary: Get Acquisition config
      description: Returns the Acquisition config
      responses:
        '200':
          description: Acquisition config returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcquisitionConfig'          
        '404':
          description: No config found with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Config
      summary: Update Acquisition config
      description: Updates the Acquisition config with the provided values
      requestBody:
        description: Acquisition config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcquisitionConfig'
          application/xml:
            schema:
              $ref: '#/components/schemas/AcquisitionConfig'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AcquisitionConfig'
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: UpdateConfigError occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /configs/default:
    post:
      tags:
        - Config
      summary: Set all configs to default
      description: Sets all configs to their default values
      responses:
        '200':
          description: Config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Failed to update config
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    BasytecConfig:
      type: object
      properties:
        buffer_exp:
          type: integer
        dll:
          type: string
        enabled:
          type: boolean
        host:
          type: string
        port:
          type: integer
    GantnerConfig:
      type: object
      properties:
        buffer_exp:
          type: integer
        dll:
          type: string
        enabled:
          type: boolean
        host:
          type: string
        port:
          type: integer
    PrecitecConfig:
      type: object
      properties:
        LAI:
          type: integer
        SHZ:
          type: integer
        buffer_exp:
          type: integer
        dll:
          type: string
        enabled:
          type: boolean
        host:
          type: string
        num_sensors:
          type: array
          items:
            type: integer
        port:
          type: string
    RigConfig:
      type: object
      properties:
        rig_list:
          type: array
          items:
            $ref: '#/components/schemas/Rig'
    Rig:
      type: object
      properties:
        rig_number:
          type: string
        basytec_channel:
          type: integer
        gantner_channel:
          type: integer
        precitec0_channel:
          type: integer
        precitec1_channel:
          type: integer
        precitec2_channel:
          type: integer
        bat_id:
          type: string
        chemistry:
          type: string
        form:
          type: string
    GeneralConfig:
      type: object
      properties:
        save_loc:
          type: string
        file_name:
          type: string
    AcquisitionConfig:
      type: object
      properties:
        channels:
          type: array
          items:
            type: integer
        max_sample:
          type: integer
    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
      xml:
        name: '##default'
    Error:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: string